---
- hosts: localhost
  become: no
  vars:
    repositories: "{{ lookup('file', 'custom/repositories.yml') | from_yaml }}"
    selected_repositories: "all"
    headless_packages: "{{ lookup('file', 'custom/headless.yml') | from_yaml }}"
    headful_packages: "{{ lookup('file', 'custom/headful.yml') | from_yaml }}"
    held_packages: "{{ lookup('file', 'custom/held.yml') | from_yaml }}"
    plugins: "{{ lookup('file', 'custom/plugins.yml') | from_yaml }}"
  
  tasks:
    - name: Install oh-my-zsh
      include_tasks: plays/oh_my_zsh_play.yml

    - name: Add repositories
      include_tasks: plays/repo_play.yml
      
    - name: Get monitor flag
      include_tasks: plays/monitor_flag_play.yml

    - name: Install packages
      include_tasks: plays/install_play.yml